version: 2

sources:
 - name: adventure_works
   description: Essa é a fonte de dados do BigQuery, criada através do Stitch.
   tables:
   - name: person
     description: Essa é a tabela de Pessoa do ERP.
   tables:
   - name: product
     description: Essa é a tabela de Produto do ERP.
