WITH PRODUTO AS ( 
				-- PRODUTOS
					 SELECT ROW_NUMBER() OVER ( ORDER BY P.PRODUCTID ) SK_PRODUTO
					       ,P.PRODUCTID             AS ID_PRODUTO
					       ,P.NAME	    	        AS NOME_PRODUTO
					       ,P.PRODUCTNUMBER         AS NUMERO_PRODUTO
					       ,P.MAKEFLAG    	        AS ENTREGA_DISPONIVEL
					       ,P.FINISHEDGOODSFLAG     AS ENTREGA_FINALZIADA
					       ,P.COLOR  	 	        AS COR_PRODUTO
					       ,P.SAFETYSTOCKLEVEL      AS NIVEL_ESTOQUE_SEGURANCA
					       ,P.REORDERPOINT 		    AS PONTO_REORDENAGEM
					       ,P.LISTPRICE             AS PRECO_LISTA
					       ,P.SIZE 	                AS TAMANHO_PRODUTO
					       ,P.SIZEUNITMEASURECODE   AS TAMANHO_UNIDADE_MEDIDA
					       ,P.WEIGHTUNITMEASURECODE AS PESO_UNIDADE_MEDIDA
					       ,P.WEIGHT 		        AS PESO
					       ,P.DAYSTOMANUFACTURE     AS DIAS_FABRICACAO
					       ,P.PRODUCTLINE 	        AS LINHA_PRODUCAO
					       ,P.CLASS			        AS CLASSE
					       ,P.STYLE 		        AS ESTILO_PRODUTO
					       ,P.PRODUCTSUBCATEGORYID  AS CATEGORIA_PRODUTO
					       ,P.PRODUCTMODELID        AS MODELO_PRODUTO
					       ,P.SELLSTARTDATE         AS DATA_INICIO_VENDA
					       ,P.SELLENDDATE 	        AS DATA_FIM_VENDA
					       ,P.DISCONTINUEDDATE      AS DATA_DESCONTINUACAO
					      ,PRODUCTMODELID 		    AS DATA_MODIFICACAO
 			 	       FROM {{ source('adventure_works', 'product' )}} p )
					  WHERE P.DISCONTINUEDDATE IS NULL 
				   ORDER BY P.SELLSTARTDATE  )
SELECT * FROM PRODUTO				   
