version: 2

models: 
    - name: dim_pessoa
      description: "Esta é a tabela de dimensão de Pessoa da Adventure Works"
      columns: 
          - name: sk_pessoa
            description: "A chave surrogada da dimensão pessoa"
            tests: 
                - unique
                - not_null 
